name: C/C++ CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - 
      name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: docker.centurionx.net
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - 
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          docker.centurionx.net/plane-receiver
    - 
      name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        command: ssh ${{secrets.INTER_INTERNAL_IP}} "docker pull docker.centurionx.net/plane-receiver; docker stop interplanereceiver; docker rm interplanereceiver; docker run -p 30004:30004 --name=interplanereceiver --restart=unless-stopped -d docker.centurionx.net/plane-receiver" 
        host: ${{ secrets.HOST }}
        username: ${{secrets.CENTURION_USERNAME}}
        password: ${{secrets.CENTURION_PASSWORD}}
